<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Mon Feb 21 18:15:42 WET 2011.

define('DOMJUDGE_VERSION', '3.1.3');

define('BINDIR',      '/home/domjudge/domjudge/domserver/bin');
define('ETCDIR',      '/home/domjudge/domjudge/domserver/etc');
define('WWWDIR',      '/home/domjudge/domjudge/domserver/www');
define('LIBDIR',      '/home/domjudge/domjudge/domserver/lib');
define('LIBWWWDIR',   '/home/domjudge/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/home/domjudge/domjudge/domserver/lib/submit');
define('LOGDIR',      '/home/domjudge/domjudge/domserver/log');
define('TMPDIR',      '/home/domjudge/domjudge/domserver/tmp');
define('SUBMITDIR',   '/home/domjudge/domjudge/domserver/submissions');

define('SUBMIT_DEFAULT', 2);
define('ENABLE_CMDSUBMIT_SERVER', 0);
define('ENABLE_WEBSUBMIT_SERVER', 1);
